name: Moonshot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-moonshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Moonshot
        run: ./scripts/setup_ms_script.sh
        env:
          GITHUB_MOONSHOT_CI_REPO_LOC: ${{ secrets.GITHUB_MOONSHOT_CI_REPO_LOC }}

      # - name: Run Moonshot
      #   run: ./scripts/run_ms_script.sh
      #   env:
      #     MOONSHOT_UPDATE_ENDPOINTS_LIST: ${{ secrets.MOONSHOT_UPDATE_ENDPOINTS_LIST }}
      #     MOONSHOT_RUN_COOKBOOKS_LIST: ${{ secrets.MOONSHOT_RUN_COOKBOOKS_LIST }}

      # - name: Display Results
      #   run: ./scripts/display_ms_script.sh
      #   env:
      #     COOKBOOK_RUN_NAME: ${{ secrets.COOKBOOK_RUN_NAME }}

      # - name: Commit Results
      #   run: ./scripts/commit_ms_script.sh
      #   env:
      #     GITLAB_MOONSHOT_PROJECT_TOKEN: ${{ secrets.GITLAB_MOONSHOT_PROJECT_TOKEN }}
      #     CI_PIPELINE_ID: ${{ github.run_id }}