name: Moonshot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-moonshot:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Moonshot
        run: |
          chmod +x .github/scripts/setup_ms_script.sh
          ./.github/scripts/setup_ms_script.sh
        env:
          GITHUB_MOONSHOT_CI_REPO_LOC: ${{ vars.GH_MOONSHOT_CI_REPO_LOC }}

      - name: Run Moonshot
        run: |
          chmod +x .github/scripts/run_ms_script.sh
          ./.github/scripts/run_ms_script.sh
        env:
          AZURE_OPENAI_4O_UPDATE_ENDPOINT: ${{ secrets.AZURE_OPENAI_4O_UPDATE_ENDPOINT }}
          # MOONSHOT_UPDATE_ENDPOINTS_LIST: "python3 -m moonshot cli \"update_endpoint azure-openai-gpt4o \\\"[('max_calls_per_second',10)]\\\"\""
          MOONSHOT_UPDATE_ENDPOINTS_LIST: ${{ vars.AZURE_OPENAI_4O_UPDATE_ENDPOINT }}

      # - name: Display Results
      #   run: ./scripts/display_ms_script.sh
      #   env:
      #     COOKBOOK_RUN_NAME: ${{ secrets.COOKBOOK_RUN_NAME }}

      # - name: Commit Results
      #   run: ./scripts/commit_ms_script.sh
      #   env:
      #     GITLAB_MOONSHOT_PROJECT_TOKEN: ${{ secrets.GITLAB_MOONSHOT_PROJECT_TOKEN }}
      #     CI_PIPELINE_ID: ${{ github.run_id }}